### ISSUE TITLE
Failed Test: test_full_adapt_sampling

### ISSUE THREAD

**Issue by nascarsdale** [exoplanet-dev/exoplanet#106] opened 2020-07-20 22:11 UTC
Hi exoplanet team, 

Thanks for putting together this great tool! I am writing because I have run the tests, per the installation instructions, and failed the "test_adapt_full_sampling" (screenshot attached) for reasons that I could not discern. 

![image](https://user-images.githubusercontent.com/55105886/87990038-0ec73f00-ca98-11ea-954d-8dbfe64c7d26.png)

I have no experience using pymc3, and the root error is " AttributeError: 'WindowedDualAverageAdaptation' object has no attribute '_mu' " which I was not sure how to handle. Have any of you seen anything like this before? 

I am on exoplanet 0.3.3(.dev34+ge036bc0) (installed with pip), pymc3 3.9.2, and fastprogress 0.2.3 (the other package with an error returned in the chain). My laptop is running ubuntu 18.04. 

Thank you! 
-Nicholas

**Comment by dfm** [comment] 2020-07-21 12:23
Thanks for reporting! I'll look into this.

**Comment by dfm** [comment] 2020-07-21 13:00
Hilariously it looks like *I* introduced this regression in a pull request to PyMC3 (PyMC3 has the correct behavior now, but I was depending on the previous, incorrect, behavior here...): https://github.com/pymc-devs/pymc3/pull/3941

**Comment by dfm** [comment] 2020-07-21 16:10
This has been fixed on the `main` branch. Thanks again!

**Closed by dfm** 2020-07-21 16:10 UTC
Labels: bug
