### ISSUE TITLE
LimbDark object can't be pickled, stops sampling in the transit example

### ISSUE THREAD

**Issue by aditya-sengupta** [exoplanet-dev/exoplanet#124] opened 2020-11-10 23:01 UTC
**Describe the bug**
When trying to run `exoplanet/docs/tutorials/transit.py`, execution is stopped at the sampling stage on line 155: the stated error is `TypeError: cannot pickle 'exoplanet.theano_ops.driver.LimbDark' object`.

**To Reproduce**
`cd` into `docs/tutorials` and run `python transit.py`: output is reproduced below.
```
optimizing logp for variables: [b, r, u, logP, t0, mean]
106it [00:01, 82.32it/s, logp=2.479354e+04]
message: Desired error not necessarily achieved due to precision loss.
logp: 24787.977771807487 -> 24793.53942561123
Auto-assigning NUTS sampler...
Initializing NUTS using adapt_full...
/Users/adityasengupta/opt/anaconda3/envs/oracle/lib/python3.8/site-packages/pymc3/step_methods/hmc/quadpotential.py:503: UserWarning: QuadPotentialFullAdapt is an experimental feature
  warnings.warn("QuadPotentialFullAdapt is an experimental feature")
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [b, r, u, logP, t0, mean]
Traceback (most recent call last):
  File "transit.py", line 149, in <module>
    trace = pm.sample(
  File "/Users/adityasengupta/opt/anaconda3/envs/oracle/lib/python3.8/site-packages/pymc3/sampling.py", line 545, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "/Users/adityasengupta/opt/anaconda3/envs/oracle/lib/python3.8/site-packages/pymc3/sampling.py", line 1470, in _mp_sample
    sampler = ps.ParallelSampler(
  File "/Users/adityasengupta/opt/anaconda3/envs/oracle/lib/python3.8/site-packages/pymc3/parallel_sampling.py", line 432, in __init__
    step_method_pickled = pickle.dumps(step_method, protocol=-1)
TypeError: cannot pickle 'exoplanet.theano_ops.driver.LimbDark' object
```
**Expected behavior**
The same output as in the docs at https://docs.exoplanet.codes/en/stable/tutorials/transit/.

**Your setup (please complete the following information):**
 - Version of exoplanet: 0.4.0
 - Operating system: Mac OS Catalina v10.15.7
 - Python version & installation method (pip, conda, etc.): Python 3.8.5, installation via pip in a conda env (+ git clone to get the file)

**Additional context**

**Comment by dfm** [comment] 2020-11-11 00:16
Thanks!

This is a duplicate of #115 and it was fixed in #120. This will be included in the next release if you don't want to build from source.

**Comment by LucieScharre** [comment] 2020-11-13 22:02
Hello, 
I'm a student trying to use this package for a project. I have not used github before and am experiencing the same issue! I have tried to implement the fix #120, but am just getting new error messages. Should the approach work of just replacing exoplanet directory (installed using pip) with the new version I've downloaded from here?

I'm getting this error message then: 
ImportError: cannot import name 'driver' from 'exoplanet.theano_ops' (/Applications/anaconda3/lib/python3.7/site-packages/exoplanet/theano_ops/__init__.py)

 I'm not the most experienced coder and don't know to what extent I should around with the source code.

**Comment by aditya-sengupta** [comment] 2020-11-13 22:07
Looks like it's still running the pip installed version; try the following (in some directory you want to use for this)

`
git clone https://github.com/exoplanet-dev/exoplanet
cd exoplanet
git submodule update --init --recursive
python setup.py develop
`

**Comment by dfm** [comment] 2020-11-13 23:12
I'll also plan on making a pip release early next week so that it'll be easier to use then. Thanks for your patience!!

**Comment by LucieScharre** [comment] 2020-11-14 11:56
That would be great as I still can't get it to work, just getting new error messages... Thank both of you so much!

**Comment by LucieScharre** [comment] 2020-11-14 12:48
Are there any obvious fixes for [Errno 32] Broken pipe?

**Comment by aditya-sengupta** [comment] 2020-11-14 18:48
Have `pm.sample` use only one core

**Comment by dfm** [comment] 2020-11-15 22:27
The package on PyPI has been updated so you should be able to get the new version using

```bash
python -m pip install -U exoplanet
```

For other errors (like a broken pipe) can you open a new issue with an example that demonstrates the problem? Then it'll be easier for me to look into it!

**Comment by LucieScharre** [comment] 2020-11-16 12:03
It now works with the new version! Thank you for fixing it so quickly!

**Comment by LucieScharre** [comment] 2020-11-16 12:43
Do you by any chance have examples of how to fit just one planet to the data? No worries if not! Just struggling a little with a working translation to only one planet

**Comment by dfm** [comment] 2020-11-16 12:47
Take a look at the examples on the case studies page to see if those are enough to get you started: https://gallery.exoplanet.codes/en/latest/

**Closed** 2020-12-14 14:25 UTC
Labels: bug
